from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from datetime import datetime


class PDFReport:

    def __init__(self, filename, title="SmartTrafficAI Report"):
        self.filename = filename
        self.title = title
        self.styles = getSampleStyleSheet()

    def _heading(self, text):
        return Paragraph(f"<b>{text}</b>", self.styles["Heading2"])

    def _normal(self, text):
        return Paragraph(text, self.styles["BodyText"])

    def build(self, traffic_data=None, drowsiness_data=None):

        doc = SimpleDocTemplate(self.filename)

        elements = []

        elements.append(
            Paragraph(
                self.title,
                self.styles["Title"]
            )
        )

        elements.append(
            self._normal(
                f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
            )
        )

        elements.append(Spacer(1, 20))

        if traffic_data:

            elements.append(
                self._heading("Traffic Density Summary")
            )

            table_data = [
                ["Metric", "Value"]
            ]

            for key, value in traffic_data.items():
                table_data.append([str(key), str(value)])

            table = Table(table_data)

            table.setStyle(
                TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                ])
            )

            elements.append(table)
            elements.append(Spacer(1, 20))

        if drowsiness_data:

            elements.append(
                self._heading("Driver Drowsiness Summary")
            )

            table_data = [
                ["Metric", "Value"]
            ]

            for key, value in drowsiness_data.items():
                table_data.append([str(key), str(value)])

            table = Table(table_data)

            table.setStyle(
                TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.darkred),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                ])
            )

            elements.append(table)

        elements.append(Spacer(1, 20))

        elements.append(
            Paragraph(
                "Generated by SmartTrafficAI",
                self.styles["Italic"]
            )
        )

        doc.build(elements)


if __name__ == "__main__":

    traffic = {
        "Vehicle Count": 27,
        "Cars": 16,
        "Motorcycles": 5,
        "Buses": 3,
        "Trucks": 3,
        "Density": "HIGH"
    }

    drowsiness = {
        "EAR": 0.19,
        "Blink Count": 46,
        "Closed Frames": 22,
        "Alert": "DROWSY"
    }

    report = PDFReport("sample_report.pdf")

    report.build(
        traffic_data=traffic,
        drowsiness_data=drowsiness
    )

    print("PDF Report Created.")